Fix the cookie-jar and validate the session

diff --git a/charts/gitlab/charts/unicorn/templates/tests/tests.yaml b/charts/gitlab/charts/unicorn/templates/tests/tests.yaml
--- a/charts/gitlab/charts/unicorn/templates/tests/tests.yaml
+++ b/charts/gitlab/charts/unicorn/templates/tests/tests.yaml
@@ -8,10 +8,24 @@ data:
     set -e
     echo 'Start Test'
     workhorse_service="{{ template "fullname" . }}:{{ .Values.service.workhorseExternalPort }}"
+
     signin_url="http://$workhorse_service/users/sign_in"
-    echo "Testing login page: $signin_url"
-    csrf=$(curl $signin_url --fail -c cookies.txt -s | grep -Po '<meta.*name="csrf-token".*content="\K[a-zA-Z0-9\+=\-\/]*')
-    echo "csrf: $csrf"
-    curl --fail -X POST $signin_url  -c cookies.txt -F "authenticity_token=$csrf" -F 'user[login]=root' -F "user[password]=$(cat /initial_root_password)"
+    echo "Login to create a session: $signin_url"
+    csrf=$(curl $signin_url --fail -s -c cookies.txt -s | grep -Po '<meta.*name="csrf-token".*content="\K[a-zA-Z0-9\+=\-\/]*')
+    curl --fail -X POST $signin_url -s -c cookies.txt -b cookies.txt -F "authenticity_token=$csrf" -F 'user[login]=root' -F "user[password]=$(cat /initial_root_password)"
+
+    profile_url="http://$workhorse_service/profile"
+    echo "Confirm session valid: $profile_url"
+    profile_status=$(curl -s -o profile_output -w "%{http_code}" -c cookies.txt -b cookies.txt $profile_url)
+
+    if [ "$profile_status" != "200" ]; then
+      echo "Error: Session Invalid"
+      cat profile_output
+      exit 1
+    fi
+
+    echo 'Test Passed'
+    exit 0
+
 # Leave this here - This line denotes end of block to the parser.
 {{- end }}
